### ISSUE TITLE
Problem in installation instructions

### ISSUE THREAD

**Issue by DeanLight** [insilichem/pychimera#11]
in this link https://pypi.org/project/pychimera/0.2.0/
you give the option to install pychimera manually
```
git clone https://github.com/insilichem/pychimera.git && python pychimera/setup.py install
```

however the setup script assumes that 'pychimera/platforms' exists relative to it.
Therefore, you should fix your installation instruction to include cd-ing to the pychimera directory.

**Comment by jaimergp** [comment]
Hi, thanks for the feedback.

Latest version is [0.2.4](https://pypi.org/project/pychimera/0.2.4/), which does not include any instructions in the PyPI project -- documentation is now available at [readthedocs](http://pychimera.readthedocs.io). That said, the installation instructions there have the same problem. I will update it soon.

Thanks,
Jaime.
