### ISSUE TITLE
Opening the reply log in --gui mode

### ISSUE THREAD

**Issue by julistanley** [insilichem/pychimera#14]
Hello! This is more of a question than an issue. 

I'm working with a codebase that includes some Chimera scripts, but they rely heavily on the output from the Reply Log. I usually call them with `chimera --start "Attribute Calculator" --start "Reply Log" --script "chimera_script.py"`. 

If I understand correctly, I might eventually be able to rewrite those scripts without relying the Reply Log (although my supervisor says that he tried to do that back in 2016 and wasn't able to). 

In the meantime, it would be great to be able to run those scripts with pychimera. I can run pychimera in gui mode with `pychimera --gui chimera_script.py` successfully, but have not figured out how to open the Reply Log from there. Is there a way to do that?

**Comment by jaimergp** [comment]
In principle, command line arguments not understood by pychimera will be
forwarded to the normal chimera exe, but this is something I have not
tested. Can you try adding the needed --start options before the script
filename? An alternative way would be to invoke the Reply Log using a
Python call within your script (I recall seeing something about that in the
chimera.extension module).

**Comment by julistanley** [comment]
>In principle, command line arguments not understood by pychimera will be
forwarded to the normal chimera exe, but this is something I have not
tested. Can you try adding the needed --start options before the script
filename? 

Oh, brilliant. Yeah, `pychimera --gui --start "Reply Log" --start "Attribute Calculator" chimera_script.py` works beautifully (and I feel a bit silly for not trying it earlier). Thank you!

(P.S. I looked a bit for a way to invoke Reply Log using a python call with chimera.extension, but wasn't able to find anything. I'm still very new to Chimera, though, and might stumble upon it. If I do, I'll try to remember to come back and make a comment on this issue in case anyone is reading this in \~the future\~).
