### ISSUE TITLE
pcre==8.39 not available anymore

### ISSUE THREAD

**Issue by vicruiser** [insilichem/pychimera#17]
Hi, 
I'm trying to satisfy pychimera dependency by installing pcre 8.39 but it seems it's not available in public repositories anymore. Is there any workaround for this?. 

Thanks

**Comment by jaimergp** [comment]
`conda-forge` [has](https://anaconda.org/conda-forge/pcre/files?version=8.39) it!

```
conda install -c conda-forge pcre=8.39
```

**Comment by vicruiser** [comment]
Perfect, thanks! I didn't know about this. It works perfectly now :)
